#!/usr/bin/env node
const fs = require('fs/promises');
const compile = require('./compiler.js');
const importHandler = require('./importHandler.js');
const args = process.argv.slice(2);

if (args[0] == '-h' || args[0] == '--help') {
    fs.readFile(`${__dirname}/helpMessage.txt`, "utf-8").then((help) => {
        console.log(help);
    });
    return;
}

if (args[0][0] == '-') return;

if (!(args[1] && args[1].match(/\S/)))
    args[1] = args[0].replace(".item", ".txt");

fs.readFile(args[0], "utf-8").then((file) => {
    let final = "";
    function write(n) { final += n; }
    importHandler(file).then((imports) => {
        console.log(`Compiling from ${args[0]} to ${args[1]}`);
        eval(imports + compile(file));
        fs.writeFile(args[1], final);
        console.log("Compiled.");
    });
});